apps/urls.py
from django.conf.urls import url
from apps.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index_view'),
    url(r'news/$', NewsList.as_view(), name='new_view'),
    url(r'case/$', CaseList.as_view(), name='case_view'),
    url(r'common/(?P<slug>\w+)/$', CommonView.as_view(), name='common_view'),
    url(r'contact/(?P<slug>\w+)/$', ContactView.as_view(), name='contact_view'),
    url(r'news/(?P<pk>[0-9]+)/$', NewsDetailed.as_view(), name='new_details'),
    url(r'honor/$', HonorListView.as_view(), name='honor_view'),
    url(r'product/$', ProductList.as_view(), name='product_view'),
    url(r'leavemessage/$', leaveMessage, name='leave-message'),
    url(r'product/(?P<pk>[0-9]+)/$', ProductDetailed.as_view(), name="product_details")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecosys/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('apps.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# RichTextUploadingField 支持图片上传

LANGUAGE= {
    1: '中文',
    2: 'English',
}


class Images(models.Model):
    """ 网站图片设置
    底部 微信公众号 和 其他类型的图片
    """
    name = models.CharField(max_length=100, verbose_name='图片名称')
    img = models.ImageField(upload_to='img/other/',
        default='/images/img/other/default.jpg', verbose_name='展示图片')

    class Meta:
        verbose_name_plural = verbose_name = '图片配置'

    def __str__(self):
        return "%s" % self.name

class File(models.Model):
    """ 文件
    """
    name = models.CharField(max_length=100, verbose_name='文件名称')
    files = models.FileField(upload_to='file/',
        default='/images/file/default.video', verbose_name='文件')
    img = models.ImageField(upload_to='img/product/',
        default='/images/img/product/default.jpg', verbose_name='展示图片')

    class Meta:
        verbose_name_plural = verbose_name = '文件'

    def __str__(self):
        return "%s" % self.name


class NavUrls(models.Model):
    url = models.CharField(max_length=40, verbose_name='指向地址', help_text="该导航栏指向的地址")
    name = models.CharField(max_length=40, verbose_name='url 名称')

    class Meta:
        verbose_name_plural = verbose_name = '导航栏 URL配置'

    def __str__(self):
        return "%s" % self.name


class Nav(models.Model):
    name = models.CharField(max_length=40, verbose_name='导航条名称')
    introduction = models.CharField(max_length=100, null=True, blank=True, verbose_name='简介')
    priority = models.SmallIntegerField(default=1, verbose_name='排列顺序')
    url = models.ForeignKey(NavUrls, verbose_name='url')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = "导航条"

    def __str__(self):
        return "%s" % self.name


class NavImages(models.Model):
    """ 导航栏图片
    """
    nav = models.ForeignKey(Nav, verbose_name='选择导航栏')
    img = models.ImageField(upload_to='img/nav/',
        default='/static/img/nav/default.jpg', verbose_name='首页轮播图片')
    priority = models.SmallIntegerField(default=0, verbose_name='图片更换顺序',
                               help_text='数字越大, 优先级越高')

    class Meta:
        verbose_name_plural = verbose_name = '网站头部图片设置'

    def __str__(self):
        return "%s" % self.nav


class Carousel(models.Model):
    """ 首页轮播图
    """
    img = models.ImageField(upload_to='img/carousel/',
        default='/static/img/carousel/default.jpg', verbose_name='首页轮播图片')
    priority = models.SmallIntegerField(default=0, verbose_name='图片更换顺序',
                               help_text='数字越大, 优先级越高')

    class Meta:
        verbose_name_plural = verbose_name = '首页轮播图片设置'

    def __str__(self):
        return "%s" % self.img


class News(models.Model):

    NEWS = {
        0: '公司新闻',
        1: '行业新闻',
    }
    nav = models.ForeignKey(Nav, verbose_name='类别')
    title = models.CharField(max_length=100, verbose_name='标题')
    content = RichTextUploadingField(verbose_name='内容')
    types = models.IntegerField(default=0, choices=NEWS.items(),
                                    verbose_name='新闻类别')
    img = models.ForeignKey(Images, blank=True, null=True, verbose_name='首页新闻展示图片')
    pub_time = models.DateTimeField('发布时间', auto_now_add=True)
    view_times = models.IntegerField(default=1, verbose_name='阅读次数')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '资讯'
        ordering = ['-pub_time']


    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('new_view')


    def __str__(self):
        return "%s" % self.title


class Jobs(models.Model):
    name = models.CharField(max_length=100, verbose_name='招聘职位')
    department = models.CharField(max_length=100, verbose_name='招聘部门')
    degree = models.CharField(max_length=100, verbose_name='学历要求')
    num = models.SmallIntegerField(verbose_name='招聘人数', default=1)
    pub_time = models.DateTimeField(auto_now_add=True)
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '招聘信息'
        ordering = ['-pub_time']

    def __str__(self):
        return "%s" % self.name


class ProductTypes(models.Model):
    """ 产品类别
    """
    name = models.CharField(max_length=100, verbose_name='类别')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    def __str__(self):
        return "%s" % self.name


class Product(models.Model):
    types = models.ForeignKey(ProductTypes, verbose_name='类别')
    name = models.CharField(max_length=100, verbose_name='产品名称')
    version = models.CharField(max_length=100, default='', verbose_name='产品型号')
    introduce = RichTextUploadingField(verbose_name='简介')
    pub_time = models.DateTimeField(auto_now_add=True)
    img = models.ImageField(upload_to='img/product/',
        default='/images/img/product/default.jpg', verbose_name='产品图片')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '产品'

    def __str__(self):
        return "%s" % self.name


class FileDown(models.Model):
    name = models.CharField(max_length=100, verbose_name='文件名')
    update_time = models.DateTimeField(auto_now_add=True, verbose_name='更新时间')
    down_times = models.IntegerField(verbose_name='下载次数')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')
    files = models.ForeignKey(File, verbose_name='文件')

    class Meta:
        verbose_name_plural = verbose_name = '文件下载'

    def __str__(self):
        return "%s" % self.name


class LeaveMessage(models.Model):
    title = models.CharField(max_length=20, blank=True, null=True, verbose_name='留言标题')
    nickname = models.CharField(max_length=20, verbose_name='用户昵称')
    telephone = models.CharField(max_length=20, verbose_name='电话号码')
    email = models.EmailField(blank=True, null=True, verbose_name='电子邮箱')
    qq = models.CharField(max_length=13, verbose_name='在线QQ')
    time = models.DateTimeField(verbose_name='留言时间', auto_now=True)
    content = models.TextField(verbose_name='留言类容')

    class Meta:
        verbose_name_plural = verbose_name = '留言板'

    def __str__(self):
        return "%s" % self.title


class SubTitle(models.Model):
    name = models.CharField(max_length=40, verbose_name='标题名称')
    nav = models.ForeignKey(Nav, verbose_name='选择导航栏')
    introduce = models.TextField(verbose_name='简介', blank=True, null=True, help_text="首页显示的简介")
    content = RichTextUploadingField(verbose_name='内容')
    top = models.BooleanField(verbose_name='是否置顶', default=False,
        help_text='选择置顶,此文章在该专栏下,优选展示')
    img = models.ForeignKey(Images, blank=True, null=True, verbose_name='图片')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '子标题'

    def __str__(self):
        return "%s" % self.name


class Honor(models.Model):
    name = models.CharField(max_length=250, verbose_name='名称')
    img = models.ImageField(upload_to='images/honor/',
        default='/images/logs/default.jpg',verbose_name='荣誉图片')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '公司荣誉'

    def __str__(self):
        return "%s" % self.name


class SysConfig(models.Model):
    logo = models.ImageField(upload_to='images/logos/',
        default='/images/logs/default.jpg', verbose_name='网站logo')
    title = models.CharField(max_length=255, default='', verbose_name='网站名称')
    copyrights = models.CharField(max_length=255, default='', verbose_name='版权信息')
    fax = models.CharField(max_length=15, blank=True, null=True, verbose_name='企业传真')
    email = models.CharField(max_length=30, verbose_name='邮箱')
    address = models.CharField(max_length=255)
    service_phone = models.CharField(max_length=15, verbose_name='服务热线')
    telephone = models.CharField(max_length=11, verbose_name='手机号码', help_text="信息咨询手机号")
    qq = models.IntegerField(blank=True, null=True, verbose_name='QQ 号码')
    business_phone = models.CharField(max_length=15, verbose_name='招商电话')
    record = models.CharField(max_length=255, default='', verbose_name='备案号')
    public = models.ImageField(upload_to='images/wx/',
        default='/images/logs/default.jpg',verbose_name='公众号')
    subscribe = models.ImageField(upload_to='images/wx/',
        default='/images/logs/default.jpg',verbose_name='订阅号')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '网站配置'

    def __str__(self):
        return "%s" % self.title

class WxImage(models.Model):
    name = models.CharField(max_length=250, verbose_name='名称')
    img = models.ForeignKey(Images, verbose_name='图片')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '微信图片设置'

    def __str__(self):
        return "%s" % self.name


class CompanyImage(models.Model):
    """ 企业简介
    """
    name = models.CharField(max_length=100, verbose_name='名称')
    acronym = models.CharField(max_length=100, verbose_name='英文名称')
    intro = models.TextField(verbose_name='简介')
    img = models.ImageField(verbose_name='图片',upload_to='images/company/',
        default='/images/logs/default.jpg')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')


    class Meta:
        verbose_name_plural = verbose_name = '企业简介'

    def __str__(self):
        return "%s" % self.name

apps/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load static from staticfiles %}
    <meta charset="UTF-8">
    <title>{{website_info.title}}</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1,  minimum-scale=1, maximum-scale=1,user-scalable=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.bootcss.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static "javascript/layerslider/css/layerslider.css" %}"/>
    <link rel="stylesheet" href="{% static "javascript/owl/owl.carousel.css" %}"/>
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "javascript/layerslider/skins/v5/skin.css" %}"/>
    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="{%static "javascript/layerslider/js/greensock.js" %}"></script>
    <script src="{%static "javascript/layerslider/js/layerslider.kreaturamedia.jquery.js" %}"></script>
    <script src="{%static "javascript/layerslider/js/layerslider.transitions.js" %}"></script>
    <script src="{%static "javascript/owl/owl.carousel.min.js" %}"></script>
    <script src="{%static "javascript/jwplayer/jwplayer.js" %}"></script>
    {%block head%} {% endblock %}

</head>


<body>
<div>
    <!-- 导航栏 网站顶部-->
    {% include "./include/nav.html"%}

    {% include "./include/carousel.html"%}
    <!-- 首页展示 -->
    <div class="content">
        <div class="container">
            {%block main%} {% endblock %}
        </div>
    <!-- 脚部-->
    {% include "./include/footer.html"%}
    </div>

</div>
</body>

<script>
    $(function() {
        if(!$('.h-n-small').is(':hidden')) {
            $('.h-n-s-title p').bind('click', function () {
                $('.h-n-small ul').slideToggle(500);
            });
        }
        //幻灯片
        $("#layerslider").layerSlider({
            pauseOnHover: true,
            responsive: false,
            responsiveUnder: 1920,
            layersContainer: 1920,
            navPrevNext: true,
            navStartStop: false,
            navButtons: true,
            showBarTimer: true,
            showCircleTimer: false,
            tnWidth: 100,
            tnActiveOpacity: 10,
            hoverBottomNav: true,
            globalBGColor: '#fff',
            towWaySlideshow: true,
            autoStart: true,
            skinsPath: '/static/javascript/layerslider/skins/',
            skin: 'v5'
        });
        //选项卡
        $('.c-e-lists li').hover(function(){
           $(this).addClass('active').siblings().removeClass('active');
            var _index = $(this).index(),_width = $('.c-e-main').height();
            $('.c-e-m-animate').animate({marginTop: - _index * _width},200, 'swing');
        });
        //焦点图
        if(!$('#owlcarousel').is(':hidden')) {
            $('#owlcarousel').owlCarousel({
                items: 1,
                itemsDesktop: [1000, 1], // between 1000px and 901px
                itemsDesktopSmall: [900, 1], // betweem 900px and 601px
                itemsTablet: [600, 1], // between 600 and 0
                autoPlay: 6000,
                navigation: true,
                pagination: false,
                paginationSpeed: 800,
                rewindSpeed: 800,
                slideSpeed: 800
            });
        }
        //视频
        if(!$('.c-n-flash').is(':hidden')){
            jwplayer('c-n-flash').setup({
                'flashplayer': '/static/jwplayer/jwplayer.flash.swf',
                'image': '/static/images/news-lists-first.jpg',
                'id': 'playerID',
                'width': '100%',
                'aspectratio':'10:8',
                'file': '/static/video/video.mp4'
            });
        }
        //产品
        if(!$('#c-p-lists').is(':hidden')) {
            $('#c-p-lists').owlCarousel({
                items: 4,
                itemsDesktop: [1000, 1], // between 1000px and 901px
                itemsDesktopSmall: [900, 3], // betweem 900px and 601px
                itemsTablet: [600, 1], // between 600 and 0
                autoPlay: false,
                navigation: true,
                pagination: true,
                paginationSpeed: 800,
                rewindSpeed: 800,
                slideSpeed: 800
            });
        }
        //cookie
        $('.eng-cookie a').bind('click', function(){
            var _cookie = getCookie("language"),
                _language = $(this).text();
            if( _language == 'English'){
                $(this).text('Chinese');
                setCookie("language", "English", 10);
                location.href = "/";
            } else if(_language == 'Chinese') {
                $(this).text('English');
                setCookie("language", "Chinese", 10);
                location.href = "/";
            }
        });
        function setCookie(name, value, expiredays) {
            var ExpireDate = new Date();
            ExpireDate.setTime(ExpireDate.getTime() + (expiredays * 60 * 1000));
            document.cookie = name + "=" + escape(value) + ((expiredays == null) ? "" : "; expires=" + ExpireDate.toGMTString()) + "; path=/";
        }
        //获取cookie
        function getCookie(name) {
            var strCookie = document.cookie;
            var arrCookie = strCookie.split(";");
            for (var i = 0; i < arrCookie.length; i++) {
                var arr = arrCookie[i].split("=");
                if (arr[0] == name) return arr[1];
            }
            return null;
        }
    });
</script>


</html>

apps/templates/case_list.html
{% extends "common.html" %}


{% block subtitle_main %}
{% url 'case_view' as case_url %}
    <h3>{{localnav.name}}</h3>
    <ul>
        <li class="active"><a href="#" target="_self">客户案例</a></li>
    </ul>
{% endblock %}



{% block subtitle_local %}
    <div class="c-m-t-path pull-right">当前位置：{{localnav.name}} > {{local_news_value}} • 摩力顿</div>
    <h4>{{localnav.name}}</h4>
{% endblock %}


{% block subtitle_content %}

<div class="c-m-list">
{% for case in page_obj %}
        <div class="c-m-l-first hover_box">
            <div class="c-m-l-f-left pull-left">
               <a href="{{case.url}}" target="_self"> <img src="{{case.img.url}}" title="{{case.name}}" alt="{{case.name}}"/></a>
            </div>
            <div class="c-m-l-f-right pull-right">
                <h4>{{case.name}}</h4>
                    <p>{{case.intro}}</p>
            </div>
        </div>
{% endfor %}

   <div class="c-m-l-pagination">
        <ul>
            <li>共{{paginator.num_pages}}页记录</li>

            {% if page_obj.has_previous %}
                <li><a href="{{ request.path }}?&page={{ page_obj.previous_page_number }}" target="_self">上一页</a></li>
            {%else%}
                <li><a href="#" target="_self">上一页</a></li>
            {% endif %}

            {%for num in page_obj.paginator.page_range %}
                {%if num == page_obj.number %}
                    <li class="active"><a href="#" target="_self">{{num}}</a></li>
                {%else%}
                    <li><a href="{{ request.path }}?page={{ num }}&nav_id={{localnav.id}}" target="_self">{{num}}</a></li>
                {%endif%}
            {%endfor%}

            {% if page_obj.has_next %}
               <li> <a href="{{ request.path }}?page={{ page_obj.next_page_number }}&nav_id={{localnav.id}}" target="_self">下一页</a></li>
            {%else%}
               <li> <a href="#" target="_self">下一页</a></li>
            {% endif %}

        </ul>
    </div>
{% endblock %}

apps/templates/common.html
{% extends "./base.html" %}
{% url 'common_view' as common_url %}
{%block main%}
<div class="row">
    <div class="col-md-3 col-lg-3">
        <div class="sides-nav">
            {%block subtitle_main %}
            <h3>{{local.nav.name}}</h3>
            <ul>
                {% for subtitle in subtitle_lists %}
                    {% if local.id == subtitle.id %}
                        <li class="active"><a href="{{common_url}}?nav_id={{subtitle.nav.id}}&subtitle={{subtitle.id}}" target="_self">{{subtitle.name}}</a></li>
                    {%else%}
                        <li><a href="{{common_url}}?nav_id={{subtitle.nav.id}}&subtitle={{subtitle.id}}" target="_self">{{subtitle.name}}</a></li>
                    {%endif%}
                {% endfor %}
                      {%block subtitle%} {% endblock %}
            </ul>
            {% endblock %}
        </div>
        <div class="sides-contact">
            <h3>全国统一服务热线</h3>
            <p>Unified national service hotlion</p>
            <h4 class="font-color-orange">0755-88888888</h4>
        </div>
    </div>
    <div class="col-md-9 col-lg-9">
        <div class="content-main">
            <div class="c-m-title">

            {%block subtitle_local%}
                <div class="c-m-t-path pull-right">当前位置：{{local.nav.name}} > {{local.name}} • 摩力顿</div>
                <h4>{{local.name}}</h4>
            {% endblock %}

            </div>
            <br>
            {%block subtitle_content%}
            <div class="c-m-list c-m-list-note">
                    {% autoescape off%}
                        {{local.content}}
                    {% endautoescape %}
            {% endblock %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/templates/contact.html
{% extends "common.html" %}

{% block subtitle_main %}
{% url 'contact_view' as contact_url %}

    <h3>{{localnav.name}}</h3>
    <ul>
        {% for key, value in subtitle_lists %}
            {%if key in  request.path %}
                <li class="active"><a href="{% url 'contact_view' key %}?nav_id={{localnav.id}}" target="_self">{{value}}</a></li>
            {%else%}
                <li><a href="{% url 'contact_view' key %}?nav_id={{localnav.id}}" target="_self">{{value}}</a></li>
            {%endif%}
        {% endfor %}
    </ul>
{% endblock %}



{% block subtitle_local %}
    <div class="c-m-t-path pull-right">当前位置：{{localnav.name}} >  {{subtitle}} • 摩力顿</div>

    <h4>{{localnav.name}}</h4>
{% endblock %}


{% block subtitle_content %}

    {% include  include_html %}

{% endblock %}

apps/templates/index.html
{% extends "./base.html" %}
{% load static from staticfiles %}
{% load  remainder %}
{%block main%}

<div class="c-c-mobile-product">
    <div class="c-c-m-p-title">
        <h2>产品展示</h2>
        <span>
            <i class="iconfont">&#xe611;</i>
        </span>
    </div>
    <div class="c-c-m-p-lists">
    {% for product in product_list %}
        <div class="c-c-m-p-l-list">
            <a href="{% url 'product_details' product.id %}?nav_id={{product_nav.id}}"><img src="{{product.img.url}}" alt="{{product.name}}"/></a>
            <p>{{product.name}}</p>
        </div>
    {%endfor%}
    </div>

</div>
<div class="c-c-mobile-nav">
    <div>
        <a href="#" target="_self">
            <i class="iconfont">&#xe604;</i>
            <h5>首页</h5>
        </a>
    </div>
    <div>
        <a href="/news/?nav_id=3" target="_self">
            <i class="iconfont">&#xe60a;</i>
            <h5>新闻</h5>
        </a>
    </div>
    <div>
        <a href="/common/message/?nav_id=2" target="_self">
            <i class="iconfont">&#xe603;</i>
            <h5>关于</h5>
        </a>
    </div>
    <div>
        <a href="/contact/message/?nav_id=7" target="_self">
            <i class="iconfont">&#xe608;</i>
            <h5>留言</h5>
        </a>
    </div>
</div>
<div class="c-c-mobile-news">
    <div class="c-c-m-p-title">
        <h2>新闻动态</h2>
        <span>
            <i class="iconfont">&#xe601;</i>
        </span>
    </div>
    <div class="c-c-m-n-lists">
        <ul>
        {% for new in news_list %}
        <div class="c-n-item">
           {%if forloop.counter <= 4 %}
                <li><i></i><a href="{% url 'new_details' new.id %}?nav_id={{new_nav.id}}" target="_self">{{new.title}}</a></li>
           {%endif%}
        </div>
        {%endfor%}
        </ul>
    </div>
</div>

<div class="c-enterprise">
        <div class="row">
            <div class="col-md-4 col-lg-4">
                <div class="c-e-table">
                    <ul class="c-e-lists">
                        {% for intro in company_list %}
                            {% if forloop.counter = 2 %}
                                <li class="active">
                            {%else%}
                                <li>
                            {%endif%}
                                    <div class="c-e-l-icon">
                                        <img src="{%static "/static/images/index-icon1.jpg" %} " alt="图标"/>
                                    </div>
                                    <div class="c-e-l-content">
                                        <h3>{{intro.name}}</h3>
                                        <h4>{{intro.acronym}}</h4>
                                        <p>{{intro.intro}}</p>
                                    </div>
                                </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="col-md-8 col-lg-8">
                <div class="c-e-main">
                    <ul class="c-e-m-animate">
                    {% for intro in company_list %}
                        <li>
                            <h3>{{intro.name}}</h3>
                            <h4>{{intro.acronym}}</h4>
                                 <img src="{{intro.img.url}}" alt="{{intro.name}}"/>
                            <p>{{intro.intro}}</p>
                        </li>
                    {%endfor%}
                    </ul>
                </div>
            </div>
        </div>
</div>

<div class="c-strength">
    <div class="c-s-title">
        <h2>{{strength_nav.name}} <small>{{strength_nav.introduction}}</small></h2>
    </div>
    <div class="row">
        {% for subtitle in subtitle_list %}
            <div class="col-md-3 col-lg-3">
                <div class="c-s-lists">
                    <img src="{{subtitle.img.img.url}}" alt="简介"/>
                    <div class="c-s-l-content">
                        <span>0{{forloop.counter}}</span>
                        <h4>{{subtitle.name}}</h4>
                        <div class="c-e-l-c-btn">
                            <a href="{{strength_nav.url.url}}?nav_id={{subtitle.nav.id}}&subtitle={{subtitle.id}}" target="_self">查看更多 +</a>
                        </div>
                        {% autoescape off %}
                            <p>{{subtitle.content |  striptags | slice:"150"}}</p>
                        {%endautoescape%}
                    </div>
                </div>
            </div>
        {%endfor%}
    </div>
</div>

<div class="c-news">
    <div class="c-s-title">
        <h2>{{new_nav.name}} <small>{{new_nav.introduction}}</small></h2>
    </div>
    <div class="row">
        <div class="col-md-8 col-lg-8">
            <div id="owlcarousel" class="owl-carousel">
                {% for new in news_img %}
                    <div class="c-n-item">
                        <img src="{{new.img.img.url}}" alt="图片"/>
                             {% for key, value in new.NEWS.items %}
                                   {%if key == new.types %}
                                          <p>{{value}}:{{new.title}}</p>
                                   {%endif%}
                             {%endfor%}
                        <span></span>
                    </div>
                {%endfor%}
            </div>
        </div>
        <div class="col-md-4 col-lg-4">
            <div id="c-n-flash">加载中...</div>
            <div class="c-n-btn">
                <a href="#" target="_self">了解更多 ></a>
            </div>
        </div>
    </div>
    <div class="row">
        {% for new in news_list %}
            <div class="col-md-3 col-lg-3">
                <div class="c-n-lists">
                    <span>{{forloop.counter | conver_language}}</span>
                    <dl>
                        <dt><a href="{% url 'new_details' new.id %}?nav_id={{new_nav.id}}" target="_self">{{new.title}}</a></dt>
                        {% autoescape off%}
                        <small><dd>{{new.content | striptags | slice:"110"}}
                        {% endautoescape %}
                            {% if new.content|length > 100 %}
                                ...
                            {% endif %}
                        </dd></small>
                    </dl>
                    <p>[{{new.pub_time |date:"Y-m-d"}}]</p>
                </div>
            </div>
        {%endfor%}
    </div>
</div>

<div class="c-product">
    <div class="c-s-title">
        <h2>{{product_nav.name}} <small>{{product_nav.introduction}}</small></h2>
    </div>
    <div class="row">
        <div id="c-p-lists" class="owl-carousel">
        {% for product in product_list %}
            <div class="col-md-12 col-lg-12">
                <div class="c-p-l-list hover_box">
                    <a href="{% url 'product_details' product.id %}?nav_id={{product_nav.id}}" target="_self">
                        <img src="{{product.img.url}}" alt="{{product.name}}"/>
                        <p>{{product.name}}</p>
                    </a>
                </div>
            </div>
        {%endfor%}
        </div>
    </div>
</div>

{% endblock %}

apps/templates/message.html
{% extends "./common.html" %}
{% url 'honor_view' as honor_url %}
{%block subtitle%}
    {%if tag == 'honor'%}
        <li class="active"><a href="#" target="_self">公司荣誉</a></li>
    {%else%}
        <li><a href="/honor/?nav_id={{local.nav.id}}" target="_self">公司荣誉</a></li>
    {%endif%}
{% endblock %}