apps/urls.py
from django.conf.urls import url
from apps.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index_view'),
    url(r'news/$', NewsList.as_view(), name='new_view'),
    url(r'case/$', CaseList.as_view(), name='case_view'),
    url(r'common/(?P<slug>\w+)/$', CommonView.as_view(), name='common_view'),
    url(r'contact/(?P<slug>\w+)/$', ContactView.as_view(), name='contact_view'),
    url(r'news/(?P<pk>[0-9]+)/$', NewsDetailed.as_view(), name='new_details'),
    url(r'honor/$', HonorListView.as_view(), name='honor_view'),
    url(r'product/$', ProductList.as_view(), name='product_view'),
    url(r'leavemessage/$', leaveMessage, name='leave-message'),
    url(r'product/(?P<pk>[0-9]+)/$', ProductDetailed.as_view(), name="product_details")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecosys/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('apps.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# RichTextUploadingField 支持图片上传

LANGUAGE= {
    1: '中文',
    2: 'English',
}


class Images(models.Model):
    """ 网站图片设置
    底部 微信公众号 和 其他类型的图片
    """
    name = models.CharField(max_length=100, verbose_name='图片名称')
    img = models.ImageField(upload_to='img/other/',
        default='/images/img/other/default.jpg', verbose_name='展示图片')

    class Meta:
        verbose_name_plural = verbose_name = '图片配置'

    def __str__(self):
        return "%s" % self.name

class File(models.Model):
    """ 文件
    """
    name = models.CharField(max_length=100, verbose_name='文件名称')
    files = models.FileField(upload_to='file/',
        default='/images/file/default.video', verbose_name='文件')
    img = models.ImageField(upload_to='img/product/',
        default='/images/img/product/default.jpg', verbose_name='展示图片')

    class Meta:
        verbose_name_plural = verbose_name = '文件'

    def __str__(self):
        return "%s" % self.name


class NavUrls(models.Model):
    url = models.CharField(max_length=40, verbose_name='指向地址', help_text="该导航栏指向的地址")
    name = models.CharField(max_length=40, verbose_name='url 名称')

    class Meta:
        verbose_name_plural = verbose_name = '导航栏 URL配置'

    def __str__(self):
        return "%s" % self.name


class Nav(models.Model):
    name = models.CharField(max_length=40, verbose_name='导航条名称')
    introduction = models.CharField(max_length=100, null=True, blank=True, verbose_name='简介')
    priority = models.SmallIntegerField(default=1, verbose_name='排列顺序')
    url = models.ForeignKey(NavUrls, verbose_name='url')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = "导航条"

    def __str__(self):
        return "%s" % self.name


class NavImages(models.Model):
    """ 导航栏图片
    """
    nav = models.ForeignKey(Nav, verbose_name='选择导航栏')
    img = models.ImageField(upload_to='img/nav/',
        default='/static/img/nav/default.jpg', verbose_name='首页轮播图片')
    priority = models.SmallIntegerField(default=0, verbose_name='图片更换顺序',
                               help_text='数字越大, 优先级越高')

    class Meta:
        verbose_name_plural = verbose_name = '网站头部图片设置'

    def __str__(self):
        return "%s" % self.nav


class Carousel(models.Model):
    """ 首页轮播图
    """
    img = models.ImageField(upload_to='img/carousel/',
        default='/static/img/carousel/default.jpg', verbose_name='首页轮播图片')
    priority = models.SmallIntegerField(default=0, verbose_name='图片更换顺序',
                               help_text='数字越大, 优先级越高')

    class Meta:
        verbose_name_plural = verbose_name = '首页轮播图片设置'

    def __str__(self):
        return "%s" % self.img


class News(models.Model):

    NEWS = {
        0: '公司新闻',
        1: '行业新闻',
    }
    nav = models.ForeignKey(Nav, verbose_name='类别')
    title = models.CharField(max_length=100, verbose_name='标题')
    content = RichTextUploadingField(verbose_name='内容')
    types = models.IntegerField(default=0, choices=NEWS.items(),
                                    verbose_name='新闻类别')
    img = models.ForeignKey(Images, blank=True, null=True, verbose_name='首页新闻展示图片')
    pub_time = models.DateTimeField('发布时间', auto_now_add=True)
    view_times = models.IntegerField(default=1, verbose_name='阅读次数')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '资讯'
        ordering = ['-pub_time']


    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('new_view')


    def __str__(self):
        return "%s" % self.title


class Jobs(models.Model):
    name = models.CharField(max_length=100, verbose_name='招聘职位')
    department = models.CharField(max_length=100, verbose_name='招聘部门')
    degree = models.CharField(max_length=100, verbose_name='学历要求')
    num = models.SmallIntegerField(verbose_name='招聘人数', default=1)
    pub_time = models.DateTimeField(auto_now_add=True)
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '招聘信息'
        ordering = ['-pub_time']

    def __str__(self):
        return "%s" % self.name


class ProductTypes(models.Model):
    """ 产品类别
    """
    name = models.CharField(max_length=100, verbose_name='类别')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    def __str__(self):
        return "%s" % self.name


class Product(models.Model):
    types = models.ForeignKey(ProductTypes, verbose_name='类别')
    name = models.CharField(max_length=100, verbose_name='产品名称')
    version = models.CharField(max_length=100, default='', verbose_name='产品型号')
    introduce = RichTextUploadingField(verbose_name='简介')
    pub_time = models.DateTimeField(auto_now_add=True)
    img = models.ImageField(upload_to='img/product/',
        default='/images/img/product/default.jpg', verbose_name='产品图片')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '产品'

    def __str__(self):
        return "%s" % self.name


class FileDown(models.Model):
    name = models.CharField(max_length=100, verbose_name='文件名')
    update_time = models.DateTimeField(auto_now_add=True, verbose_name='更新时间')
    down_times = models.IntegerField(verbose_name='下载次数')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')
    files = models.ForeignKey(File, verbose_name='文件')

    class Meta:
        verbose_name_plural = verbose_name = '文件下载'

    def __str__(self):
        return "%s" % self.name


class LeaveMessage(models.Model):
    title = models.CharField(max_length=20, blank=True, null=True, verbose_name='留言标题')
    nickname = models.CharField(max_length=20, verbose_name='用户昵称')
    telephone = models.CharField(max_length=20, verbose_name='电话号码')
    email = models.EmailField(blank=True, null=True, verbose_name='电子邮箱')
    qq = models.CharField(max_length=13, verbose_name='在线QQ')
    time = models.DateTimeField(verbose_name='留言时间', auto_now=True)
    content = models.TextField(verbose_name='留言类容')

    class Meta:
        verbose_name_plural = verbose_name = '留言板'

    def __str__(self):
        return "%s" % self.title


class SubTitle(models.Model):
    name = models.CharField(max_length=40, verbose_name='标题名称')
    nav = models.ForeignKey(Nav, verbose_name='选择导航栏')
    introduce = models.TextField(verbose_name='简介', blank=True, null=True, help_text="首页显示的简介")
    content = RichTextUploadingField(verbose_name='内容')
    top = models.BooleanField(verbose_name='是否置顶', default=False,
        help_text='选择置顶,此文章在该专栏下,优选展示')
    img = models.ForeignKey(Images, blank=True, null=True, verbose_name='图片')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '子标题'

    def __str__(self):
        return "%s" % self.name


class Honor(models.Model):
    name = models.CharField(max_length=250, verbose_name='名称')
    img = models.ImageField(upload_to='images/honor/',
        default='/images/logs/default.jpg',verbose_name='荣誉图片')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '公司荣誉'

    def __str__(self):
        return "%s" % self.name


class SysConfig(models.Model):
    logo = models.ImageField(upload_to='images/logos/',
        default='/images/logs/default.jpg', verbose_name='网站logo')
    title = models.CharField(max_length=255, default='', verbose_name='网站名称')
    copyrights = models.CharField(max_length=255, default='', verbose_name='版权信息')
    fax = models.CharField(max_length=15, blank=True, null=True, verbose_name='企业传真')
    email = models.CharField(max_length=30, verbose_name='邮箱')
    address = models.CharField(max_length=255)
    service_phone = models.CharField(max_length=15, verbose_name='服务热线')
    telephone = models.CharField(max_length=11, verbose_name='手机号码', help_text="信息咨询手机号")
    qq = models.IntegerField(blank=True, null=True, verbose_name='QQ 号码')
    business_phone = models.CharField(max_length=15, verbose_name='招商电话')
    record = models.CharField(max_length=255, default='', verbose_name='备案号')
    public = models.ImageField(upload_to='images/wx/',
        default='/images/logs/default.jpg',verbose_name='公众号')
    subscribe = models.ImageField(upload_to='images/wx/',
        default='/images/logs/default.jpg',verbose_name='订阅号')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '网站配置'

    def __str__(self):
        return "%s" % self.title

class WxImage(models.Model):
    name = models.CharField(max_length=250, verbose_name='名称')
    img = models.ForeignKey(Images, verbose_name='图片')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')

    class Meta:
        verbose_name_plural = verbose_name = '微信图片设置'

    def __str__(self):
        return "%s" % self.name


class CompanyImage(models.Model):
    """ 企业简介
    """
    name = models.CharField(max_length=100, verbose_name='名称')
    acronym = models.CharField(max_length=100, verbose_name='英文名称')
    intro = models.TextField(verbose_name='简介')
    img = models.ImageField(verbose_name='图片',upload_to='images/company/',
        default='/images/logs/default.jpg')
    language_id = models.SmallIntegerField(choices=LANGUAGE.items(), verbose_name='选择语言')


    class Meta:
        verbose_name_plural = verbose_name = '企业简介'

    def __str__(self):
        return "%s" % self.name

apps/templates/include/carousel.html
{% load static from staticfiles %}
{% if url == '/' %}
    <div id="layerslider" style="width: 100%; height: 1000px;">
    {% for carousel_page in carousel_page_list %}
                <div class="ls-slide" data-ls="slidedelay:4000; transition2d:5; timeshift: -1000;">
                    <img src="{{carousel_page.img.url}}" class="ls-bg" alt="图片">
                </div>
    {% endfor %}
    </div>
{% else %}
    <div id="layerslider" style="width: 100%; height: 500px;">
    {% for carousel_page in carousel_page_list %}
        <div class="ls-slide" data-ls="transition2d:5; timeshift: -1000;">
            <img src="{{carousel_page.img.url}}" class="ls-bg" alt="图片">
        </div>
    {% endfor %}
    </div>
{% endif %}

apps/templates/include/footer.html
{% load static %}
<footer class="c-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-lg-5">
                <h2>{{website_info.title}}</h2>
                <ul class="c-f-navs">
                {% for nav in nav_list%}
                    {% if request.path == nav.url.url or url == nav.url.url %}
                        <li class="active"><a href="{{nav.url.url}}?nav_id={{nav.id}}" target="_self">{{nav.name}}</a></li>
                    {% else %}
                        <li><a href="{{nav.url.url}}?nav_id={{nav.id}}" target="_self">{{nav.name}}</a></li>
                    {% endif %}
                {%endfor%}
                </ul>
                <p>版权所有：{{website_info.copyrights}}</p>
            </div>
            <div class="col-md-7 col-lg-7">
                <div class="c-f-qrcode">
                    <img src="{{website_info.subscribe.url}}" alt="欢迎关注微信"/>
                    <p>欢迎关注公司订阅号</p>
                </div>
                <div class="c-f-qrcode">
                    <img src="{{website_info.public.url}}" alt="欢迎关注微信"/>
                    <p>欢迎关注公司公众号</p>
                </div>
                <div class="c-f-messages">
                    <p>招商电话：{{website_info.business_phone}}</p>
                    <p>总公司地址：{{website_info.address}}</p>
                    <p>企业传真：{{website_info.fax}}</p>
                    <p>企业邮箱：{{website_info.email}}</p>
                </div>
            </div>
        </div>
    </div>
</footer>

        <footer class="c-c-mobile-footer">
            <div class="c-c-m-f-copyright">
                <p>版权所有: {{website_info.copyrights}}</p>
            </div>
        </footer>
        <div class="c-c-mobile-footer-fixed">
            <div class="c-c-mobile-nav">
                <div>
                    <a href="tel:{{website_info.service_phone}}" target="_self">
                        <i class="iconfont">&#xe60b;</i>
                        <h5>电话咨询</h5>
                    </a>
                </div>
                <div>
                    <a href="sms:{{website_info.telephone}}" target="_self">
                        <i class="iconfont">&#xe608;</i>
                        <h5>信息咨询</h5>
                    </a>
                </div>
                <div>
                    <a href="/contact/map/" target="_self">
                        <i class="iconfont">&#xe600;</i>
                        <h5>在线地图</h5>
                    </a>
                </div>
                <div>
                    <a href="http://wpa.qq.com/msgrd?v=3uin={{website_info.qq}}&site=qq&menu=yes" target="_self">
                        <i class="iconfont">&#xe60e;</i>
                        <h5>QQ客服</h5>
                    </a>
                </div>
            </div>
        <div>

apps/templates/include/map.html
    <iframe width="862" height="862" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://j.map.baidu.com/yJ5qB"></iframe>

apps/templates/include/message.html
{% url 'leave-message' as leave_message %}
<div class="c-m-list c-m-message">
<div class="form-inline">
    <div class="form-group">
        <label for="exampleInputName1">用户昵称: </label>
        <input type="text" name="name" value=""  class="form-control" id="exampleInputName1" placeholder="用户昵称:">
    </div>
    <div class="form-group">
        <label for="exampleInpuNumber2">联系电话: </label>
        <input type="text" name="phone" value="" class="form-control" id="exampleInpuNumber2" placeholder="手机号码:">
    </div>
    <div class="form-group">
        <label for="exampleInpuNumber3">在线Q Q: </label>
        <input type="text" name="QQ" value="" class="form-control" id="exampleInpuNumber3" placeholder="在线QQ:">
    </div>
    <div class="form-group">
        <label for="exampleInpuNumber4">电子邮箱: </label>
        <input type="text" name="Email" value="" class="form-control" id="exampleInpuNumber4" placeholder="电子邮箱:">
    </div>
    <div class="form-group">
        <label for="exampleInputName5">留言标题: </label>
        <input type="text" name="title" value="" class="form-control" id="exampleInputName5" placeholder="留言标题:">
    </div>
    <div class="form-group">
        <label for="exampleInputName6">留言内容: </label>
        <textarea rows="6" name="content" value="" cols="20" class="form-control" id="exampleInputName6" placeholder="留言内容:"></textarea>
    </div>
    <div class="form-group c-m-m-code">
        <label for="exampleInputName7"> 验证码: </label>
        <input type="text" name="code" value="" class="form-control" id="exampleInputName7" placeholder="验证码:">
        <div class="c-m-m-c-img pull-right">
            <!--<img src="images/message-code.jpg" alt="验证码"/>-->
            <span value="6789">6789</span>
            <a>看不清</a>
        </div>
    </div>
    <div class="clearfix c-m-m-submit">
        <button type="submit">发表留言</button>
    </div>
</div>
</div>
</div>
<div class="ajax-form-animation">
    <div class="a-f-a-text"></div>
</div>
<script>
//随机4位数

$('.ajax-form-animation').bind('click', function(){
    $(this).css('display','none');
});

function RndNum(n) {
        var rnd = "";
        for (var i = 0; i < n; i++)
            rnd += Math.floor(Math.random() * 10);
        return rnd;
    }
    $('.c-m-m-c-img span').text(RndNum(4));
    $('.c-m-m-c-img a').bind('click',function(){
        $('.c-m-m-c-img span').text(RndNum(4));
    });
    //验证
    $('input,textarea').blur(function(){
        var _self = $.trim($(this).val()), name = $(this).attr('name'), code = $.trim($('.c-m-m-c-img span').text());
        var regular = {
            phone:/^[1][3-8]\d{9}$/,
            QQ: /^[1-9][0-9]{5,10}/,
            Email: /^([a-z0-9][a-z0-9_\.-]+)@([a-z0-9\.-]+)\.([a-z\.]{2,6})$/
        };
        if (_self.length != 0){
            if (name == "name" || (name == "phone" && regular.phone.test(_self)) || (name == "QQ" && regular.QQ.test(_self)) || (name == "Email" && regular.Email.test(_self)) || name == "title" || name == "content" || (name == "code" && _self == code)){
                $(this).removeClass('active');
            } else {
                $(this).addClass('active');
            }
        } else {
            $(this).addClass('active');
        }
    });


   $('.c-m-m-submit button').bind('click', function(){
        var _val1 = $.trim($('#exampleInputName1').val()).length,
            _val2 = $.trim($('#exampleInpuNumber2').val()).length,
            _val3 = $.trim($('#exampleInpuNumber3').val()).length,
            _val4 = $.trim($('#exampleInpuNumber4').val()).length,
            _val5 = $.trim($('#exampleInputName5').val()).length,
            _val6 = $.trim($('#exampleInputName6').val()).length,
            _val7 = $.trim($('#exampleInputName7').val()).length,
            act = $('input,textarea').hasClass('active');
        if((_val1 && _val2 && _val3 && _val4 && _val5 && _val6 && _val7) > 0 && !act){
            $.ajax({
                type: "POST",
                url: {{leave_message}},
                data: {
                    "name": $('#exampleInputName1').val(),
                    "phone": $('#exampleInpuNumber2').val(),
                    "QQ": $('#exampleInpuNumber3').val(),
                    "Email": $('#exampleInpuNumber4').val(),
                    "title": $('#exampleInputName5').val(),
                    "content": $('#exampleInputName6').val(),
                    "code": $('#exampleInpuNumber7').val()
                },
                dataType: "json",
                beforeSend: function () {
                    $('.ajax-form-animation').css('display','block');
                    $('.ajax-form-animation .a-f-a-text').text('提交中...');
                },
                success: function (data) {
                    if(data.code == 0){
                        $('.ajax-form-animation .a-f-a-text').text('提交成功!');
                    } else if(data.code != 0) {
                        $('.ajax-form-animation .a-f-a-text').text(data.result);
                    }
                },
                error: function () {
                    $('.ajax-form-animation .a-f-a-text').text('提交失败!');
                }
            });
        } else {
            $('.ajax-form-animation').css('display','block');
            $('.ajax-form-animation .a-f-a-text').text('格式错误!');
        }

    });

</script>

apps/templates/include/nav.html
{% url 'index-view' as index_url %}
<nav class="header-nav">
    <div class="container">
        <div class="row h-n-big">
            <div class="col-md-4 col-lg-4">
                <a href="/" target="_self">
                    <img src="{{website_info.logo.url}}" alt="logo"/>
                </a>
            </div>
            <div class="col-md-8 col-lg-8">
                <ul>
                {% for nav in nav_list%}
                    {% if request.path == nav.url.url or url == nav.url.url %}
                        <li class="active"><a href="{{nav.url.url}}?nav_id={{nav.id}}" target="_self">{{nav.name}}</a></li>
                    {% else %}
                        <li><a href="{{nav.url.url}}?nav_id={{nav.id}}" target="_self">{{nav.name}}</a></li>
                    {% endif %}
                    <li>|</li>
                {%endfor%}
                   <!-- <li class="eng-cookie"><a>{{language}}</a></li> -->
                    <li><a href="#">English</a></li><-->

                </ul>
            </div>
        </div>

        <div class="h-n-small">
            <div class="h-n-s-title">
                <p></p>
                <a class="h-n-s-logo" href="/" target="_self">
                    <img src="{{website_info.logo.url}}" alt="logo"/>
                </a>
            </div>
                <ul>
                {% for nav in nav_list%}
                    {% if request.path == nav.url.url or url == nav.url.url %}
                        <li class="active"><a href="{{nav.url.url}}?nav_id={{nav.id}}" target="_self">{{nav.name}}</a></li>
                    {% else %}
                        <li><a href="{{nav.url.url}}?nav_id={{nav.id}}" target="_self">{{nav.name}}</a></li>
                    {% endif %}
                {%endfor%}

                   <!-- <li class="eng-cookie"><a>{{language}}</a></li> -->
                    <li><a href="#">English</a></li>

                </ul>
       </div>
<div>
</nav>